// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvOLlLloK3VBaAgVRIrCbugrhBX0MUMg',
    appId: '1:363755728733:web:aeb0eeeb958e554d0b42b4',
    messagingSenderId: '363755728733',
    projectId: 'mat3ami-app',
    authDomain: 'mat3ami-app.firebaseapp.com',
    storageBucket: 'mat3ami-app.firebasestorage.app',
    measurementId: 'G-54FVR5SYM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEfRb1mk3-BJIPw1QtvCrSxiN9vKgu9g',
    appId: '1:363755728733:android:8fff389bd02712b40b42b4',
    messagingSenderId: '363755728733',
    projectId: 'mat3ami-app',
    storageBucket: 'mat3ami-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-EVMLoYQR9TXZSoPwYQKtzPtberdBiw',
    appId: '1:363755728733:ios:9cdebb25e007d8dc0b42b4',
    messagingSenderId: '363755728733',
    projectId: 'mat3ami-app',
    storageBucket: 'mat3ami-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-EVMLoYQR9TXZSoPwYQKtzPtberdBiw',
    appId: '1:363755728733:ios:9cdebb25e007d8dc0b42b4',
    messagingSenderId: '363755728733',
    projectId: 'mat3ami-app',
    storageBucket: 'mat3ami-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvOLlLloK3VBaAgVRIrCbugrhBX0MUMg',
    appId: '1:363755728733:web:8dcb0fb9c6e486680b42b4',
    messagingSenderId: '363755728733',
    projectId: 'mat3ami-app',
    authDomain: 'mat3ami-app.firebaseapp.com',
    storageBucket: 'mat3ami-app.firebasestorage.app',
    measurementId: 'G-DYPQVDX3VZ',
  );
}
